// Copyright 2017 Ivan Kuchkov

#ifndef MODULES_ARITHMETIC_PARSER_INCLUDE_ARITHMETIC_CALCULATOR_H_
#define MODULES_ARITHMETIC_PARSER_INCLUDE_ARITHMETIC_CALCULATOR_H_

enum ReturnCodes {
    RESULT_SUCESS = 0,
    RESULT_BAD_ARGUMENTS,
    RESULT_ERROR_PARSING
};

int ArithmeticCalculator(int argc, const char *const *argv);

#endif  // MODULES_ARITHMETIC_PARSER_INCLUDE_ARITHMETIC_CALCULATOR_H_
