// Copyright 2017 Nesterov Alexander

#ifndef MODULES_COLOR_SPACES_INCLUDE_ABSTRACT_SPACE_H_
#define MODULES_COLOR_SPACES_INCLUDE_ABSTRACT_SPACE_H_

class AbstractSpace {
};

#endif  // MODULES_COLOR_SPACES_INCLUDE_ABSTRACT_SPACE_H_
