// Copyright 2017 Nesterov Alexander

#ifndef MODULES_COLOR_SPACE_INCLUDE_HSB_HSV_SPACE_H_
#define MODULES_COLOR_SPACE_INCLUDE_HSB_HSV_SPACE_H_

#endif  // MODULES_COLOR_SPACE_INCLUDE_HSB_HSV_SPACE_H_
